# Naive Bayes for Email Spam/Ham 

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [56]:
df = pd.read_csv('email_spam.csv')
df.head()

spam                                              email  label
0   ham  Subject: enron methanol ; meter # : 988291\r\n...      0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...      0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...      0
3  spam  Subject: photoshop , windows , office . cheap ...      1
4   ham  Subject: re : indian springs\r\nthis deal is t...      0

In [57]:
df.drop(df.index[2000:5171], inplace = True)

In [58]:
df.shape

(2000, 3)

In [59]:
df.groupby('spam').describe()

label                                   
       count mean  std  min  25%  50%  75%  max
spam                                           
ham   1437.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam   563.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [60]:
X_train, X_test, y_train, y_test = train_test_split(df.email, df.label, test_size = 0.2)

In [61]:
len(X_train)

1600

In [62]:
#X_train.values

In [63]:
from sklearn.feature_extraction.text import CountVectorizer

In [64]:
v = CountVectorizer()
v

CountVectorizer()

In [65]:
X_train_set = v.fit_transform(X_train.values)
X_train_set.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [66]:
from sklearn.naive_bayes import MultinomialNB
modelf = MultinomialNB()
modelf

MultinomialNB()

In [67]:
modelf.fit(X_train_set, y_train)

MultinomialNB()

In [90]:
email = ['how are you']
email_set = v.transform(email)

In [91]:
modelf.predict(email_set)

array([0], dtype=int64)

In [74]:
X_test_set = v.transform(X_test)
X_test_set.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [75]:
modelf.score(X_test_set, y_test)

0.9725

# Pipeline Simplification

In [107]:
from sklearn.pipeline import Pipeline
pip = Pipeline([ ('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [108]:
pip.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [109]:
pip.score(X_test, y_test)

0.9725

In [139]:
email = ['read 1000 stoires on our website now']

In [140]:
pip.predict(email)

array([1], dtype=int64)

In [105]:
pip.predict(X_test[-3:])

array([0, 0, 0], dtype=int64)

In [106]:
y_test[-3:]

1778    0
1981    0
1085    0
Name: label, dtype: int64